export const queryKeys = {
  학교리스트조회: 'getSchoolList',
  학교확인질문확인: 'getSchoolQuestion',
  마이페이지확인: 'getMyProfile',
  인증코드새로발급받기: 'getNewCode',
  확인질문수정하기: 'changeSchoolQnA',
  공지사항리스트조회: 'getNoticeList',
  공지사항상세보기: 'getNoticeDetail',
  로그인: 'login',
  아이디존재여부확인: 'checkEmailDuplicate',
  학생리스트조회: 'studentList',
  학생상세정보: 'getStudentDetail',
  공지상세보기: 'noticeDetail',
  이메일인증코드확인: 'checkEmailAuthCode',
};
