name: node.js CI

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfixes'
      - 'release/**'
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Generate Environment Variables File for Production
        env:
          REACT_APP_DOMAIN: ${{ secrets.APP_PUBLIC_URL }}
        run: |
          echo "APP_PUBLIC_URL=$APP_PUBLIC_URL" >> .env
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build Packages
        run: yarn build
