name: E2E Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfixes'
      - 'release/**'
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn dev
          test: yarn e2e
          record: true
