name: E2E Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfixes'
      - 'release/**'
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    name: End-to-End tests (web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate Environment Variables File for Production
        env:
          REACT_APP_DOMAIN: ${{ secrets.REACT_APP_DOMAIN }}
        run: |
          echo "REACT_APP_DOMAIN=$REACT_APP_DOMAIN" >> .env

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: yarn dev
          install-command: yarn install --immutable
          command-prefix: yarn dlx
          config-file: cypress.config.js
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 200
          browser: chrome
          record: true
