name: team-aliens-main-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate Environment Variables File for Production
        env:
          APP_PUBLIC_URL: ${{ secrets.SERVER_URL }}
        run: |
          echo "APP_PUBLIC_URL=$APP_PUBLIC_URL" >> .env
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: DISABLE_ESLINT_PLUGIN=true yarn build build

      - name: Cache node modulesa
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://team-aliens-admin.dsm-dms.com
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CloudFront Cache invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.ADMIN_CLOUD_FRONT_DISTRIBUTION_ID }} --paths "/*"
